"""add profile data to user profiles

Revision ID: 71d2ef35e857
Revises: 20cc75154e61
Create Date: 2026-08-13 09:43:06.327586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d2ef35e857'
down_revision: Union[str, Sequence[str], None] = '20cc75154e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'profile_data')
    # ### end Alembic commands ###
